#!/usr/bin/php
<?php
require_once __DIR__ . '/requireFile.php';

if (php_sapi_name() !== 'cli') {
    exit;
}
// var_dump($argc); //number of arguments passed 
// var_dump($argv); //the arguments passed

if (count($argv) > 1) {
    if (isset($argv[2])) {
        excute($argv[1], $argv[2]);
    }else{
        excute($argv[1], '');
    }
} else echo 'no arguments yet !!';
